---
title: "Intro into readxl"
author: "Nick Munday"
date: "December 7, 2019"
output: html_document
---

# Learning `readxl`

We are working with data and it's goinmg to be amazing!

We're going to use packages:
- tidyverse
- readxl
- writexl
- here

```{r packages}
library (tidyverse)
library (readxl)
library (writexl)
library (here)

### this is an annotation in code
```
<!-- this is to hide in non-code chunks
all html tags recognized -->

### Read in fish counts

```{r}
###Read in the fish_counts_curated.csv file
fish_counts <- read_csv(here("r-workshop-data","fish_counts_curated.csv"))
```

### Read in data from a single excel worksheet

Now, to read in an excel spreadsheet, we'll use the function `read_excel()`
``` {r}
### skip first 4 rows, replace -9999 with na
substrate_cover <- read_excel(here("r-workshop-data","substrate_cover_curated.xlsx"), 
                              skip = 4, 
                              na = "-9999")

```

### Use read_excel() to read in a range of values

``` {r}
carp_cover_2000 <- read_excel(here("r-workshop-data","substrate_cover_curated.xlsx"),
                              range = "D12:I15",
                              col_names = c("site",
                                            "transect",
                                            "quad",
                                            "side",
                                            "type",
                                            "coverage"))
```

### read in data from different tabs

``` {r}
kelp_counts <- read_excel(here("r-workshop-data","kelp_counts_curated.xlsx"),
                  )
```







